# Generated by Django 5.0.6 on 2024-07-13 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('room_applied', models.CharField(default='xxx', max_length=3)),
                ('status', models.CharField(choices=[('0', 'In Process'), ('1', 'Confirmed'), ('2', 'Canceled')], default='0', max_length=1)),
            ],
        ),
    ]
