# Generated by Django 5.0.6 on 2024-07-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.resident'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.resident')),
                ('id_type', models.CharField(choices=[('1', 'Institutional ID'), ('2', 'Aadhar Number'), ('3', 'Voter ID'), ('4', 'Driving License'), ('5', 'Passport')], max_length=1)),
                ('id_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'In Process'), ('1', 'Verified'), ('2', 'Canceled')], default='0', max_length=1)),
            ],
            options={
                'unique_together': {('id_type', 'id_number')},
            },
        ),
    ]
